"""Daemon entry point: thin shim around :func:`api.collect_all_due`.

Post-refactor (T9), this module no longer owns per-source-type collection
logic.  The single execution path is:

    daemon_tick / daemon_loop  ──►  api.collect_all_due(config)
                                       │
                                       ▼
                                LIST → DIFF → CONTENT per due subscription
                                       │
                                       ▼
                                tools.storage.persist_raw

The previous private helpers ``_collect_rss``, ``_collect_youtube``,
``_collect_browser``, and ``_collect_subscription`` are removed.  The
``_query_due_subscriptions`` SQL is no longer owned here either —
:mod:`contents_hub.api` owns the canonical due-row query
(``api._query_due_rows``).  See ``contracts.md`` (R-T7.1, R-T10.1).

External invariants preserved:

- ``daemon_loop(config, *, interval_minutes=...)`` retains its name and
  signature so the macOS LaunchAgent plist generated by
  :mod:`contents_hub.launchd` (which invokes ``python -m contents_hub.daemon
  loop``) requires no reinstallation (R-T10.1, INV-10).
- All diagnostic output flows through :mod:`logging` and is routed to the
  resolved metadata ``daemon.log`` by :func:`main` — never stdout (R-U5.2,
  INV-9).  The pre-existing ``daemon run`` text/JSON output contract is
  unchanged from a caller's perspective (R-U2.3); the underlying
  :class:`DaemonTickResult` is now the one defined in :mod:`contents_hub.api`.

Auxiliary helpers retained on this module
(``_update_subscription_success``, ``_update_subscription_error``,
``classify_error``, ``backoff_minutes``, ``_start_job_run``,
``_finish_job_run``, ``_insert_raw_item``) are scheduled for re-targeting
or deletion in later tasks (T13/T14); leaving them in place here keeps
existing tests green during the parallel-task window.
"""

from __future__ import annotations

import asyncio
import logging
import sqlite3
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Callable

from contents_hub.api import DaemonTickResult, collect_all_due
from contents_hub.config import WikiConfig

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Error classification & backoff (retained for use by lingering test paths
# until T13 re-targets the test suite onto api.collect_all_due).
# ---------------------------------------------------------------------------

BACKOFF_MINUTES = [5, 30, 120]  # 5min -> 30min -> 2h


def classify_error(error_msg: str) -> str:
    """Classify a fetch error message into a retry category.

    Returns: 'transient', 'permanent', or 'ambiguous'.
    """
    msg = error_msg.lower()

    # Permanent
    if "404" in msg or "not found" in msg:
        return "permanent"
    if "403" in msg or "forbidden" in msg:
        return "permanent"

    # Transient
    if "timeout" in msg or "timed out" in msg:
        return "transient"
    if "network" in msg or "connection" in msg:
        return "transient"
    if any(code in msg for code in ("429", "500", "502", "503")):
        return "transient"

    return "ambiguous"


def backoff_minutes(consecutive_errors: int) -> int:
    """Calculate backoff delay in minutes."""
    idx = min(consecutive_errors, len(BACKOFF_MINUTES) - 1)
    return BACKOFF_MINUTES[idx]


# ---------------------------------------------------------------------------
# Subscription bookkeeping helpers (retained so test_daemon_clear_manual_fetch
# keeps passing until T13 re-targets it onto the executor path).
# ---------------------------------------------------------------------------


def _update_subscription_success(
    conn: sqlite3.Connection,
    sub_id: int,
    new_items: int,
    interval_minutes: int,
) -> None:
    """Update subscription after successful fetch.

    Also clears `config.last_manual_fetch` so a stale failure banner from an
    earlier manual "Fetch now" click doesn't linger once a later fetch (manual
    or daemon) succeeds.
    """
    now = datetime.now(timezone.utc)
    now_iso = now.isoformat()
    conn.execute(
        """UPDATE subscriptions
           SET status = 'active',
               last_fetched_at = ?,
               last_error = '',
               consecutive_errors = 0,
               config = json_remove(config, '$.last_manual_fetch'),
               updated_at = ?
           WHERE id = ?""",
        (now_iso, now_iso, sub_id),
    )


def _update_subscription_error(
    conn: sqlite3.Connection,
    sub_id: int,
    error_msg: str,
    consecutive_errors: int,
) -> None:
    """Update subscription after failed fetch."""
    now = datetime.now(timezone.utc)
    now_iso = now.isoformat()
    error_type = classify_error(error_msg)

    if error_type == "permanent":
        conn.execute(
            """UPDATE subscriptions
               SET status = 'error',
                   last_error = ?,
                   consecutive_errors = ?,
                   last_fetched_at = ?,
                   updated_at = ?
               WHERE id = ?""",
            (error_msg, consecutive_errors, now_iso, now_iso, sub_id),
        )
    else:
        delay = backoff_minutes(consecutive_errors - 1)
        backoff_time = now + timedelta(minutes=delay)
        backoff_iso = backoff_time.isoformat()
        conn.execute(
            """UPDATE subscriptions
               SET status = 'active',
                   last_error = ?,
                   consecutive_errors = ?,
                   last_fetched_at = ?,
                   updated_at = ?
               WHERE id = ?""",
            (error_msg, consecutive_errors, backoff_iso, now_iso, sub_id),
        )


# ---------------------------------------------------------------------------
# Daemon tick (single cycle) — thin wrapper around api.collect_all_due.
# ---------------------------------------------------------------------------


async def daemon_tick(config: WikiConfig) -> DaemonTickResult:
    """Run one daemon tick by delegating to :func:`api.collect_all_due`.

    The ``DaemonTickResult`` returned is the dataclass defined in
    :mod:`contents_hub.api` (re-exported from this module for back-compat).
    """
    logger.info("daemon_tick: delegating to api.collect_all_due")
    result = await collect_all_due(config)
    logger.info(
        "daemon_tick complete: total=%d new=%d skipped=%d errors=%d in %.1fs",
        result.total, result.new, result.skipped, result.errors,
        result.duration_seconds,
    )
    return result


# ---------------------------------------------------------------------------
# Daemon loop (continuous) — entry point invoked by the launchd plist.
# Signature MUST remain stable (R-T10.1, INV-10).
# ---------------------------------------------------------------------------


async def daemon_loop(
    config: WikiConfig,
    *,
    interval_minutes: float = 30,
    max_ticks: int | None = None,
    on_complete: Callable[[DaemonTickResult], None] | None = None,
) -> None:
    """Run the daemon in a continuous loop.

    Args:
        config: Wiki configuration.
        interval_minutes: Minutes between ticks.
        max_ticks: Stop after this many ticks (None = infinite).
        on_complete: Callback after each tick completes.
    """
    tick_count = 0

    logger.info("Daemon loop started (interval=%s min)", interval_minutes)

    while True:
        result = await daemon_tick(config)

        if on_complete:
            try:
                on_complete(result)
            except Exception:  # noqa: BLE001 - on_complete must not break loop
                logger.exception("daemon_loop: on_complete callback raised")

        tick_count += 1
        if max_ticks is not None and tick_count >= max_ticks:
            logger.info("Daemon: max ticks (%d) reached, stopping", max_ticks)
            break

        await asyncio.sleep(interval_minutes * 60)


# ---------------------------------------------------------------------------
# CLI entry point — preserved verbatim for `python -m contents_hub.daemon` invoked
# by the launchd plist.  Output contract unchanged (R-U2.3 / R-T10.1).
# ---------------------------------------------------------------------------


DEFAULT_INTERVAL_MINUTES = 30


def main(argv: list[str] | None = None) -> int:
    """CLI entry point for the daemon.

    Invoked via: ``python -m contents_hub.daemon run|loop`` (and the launchd
    plist generated by :mod:`contents_hub.launchd`).
    """
    import argparse
    import json
    import sys  # noqa: F401 — kept available for future signal handling

    parser = argparse.ArgumentParser(
        description="contents-hub daemon: auto-collect from subscriptions",
    )
    parser.add_argument(
        "--vault",
        help="Obsidian vault path (default: $CONTENTS_HUB_VAULT or CWD)",
    )

    sub = parser.add_subparsers(dest="action", required=True)

    run_p = sub.add_parser("run", help="Run a single tick and exit")
    run_p.add_argument(
        "--json",
        action="store_true",
        dest="json_output",
        help="Output results as JSON",
    )

    loop_p = sub.add_parser("loop", help="Run continuously")
    loop_p.add_argument(
        "--interval",
        type=float,
        default=DEFAULT_INTERVAL_MINUTES,
        help=f"Interval in minutes (default: {DEFAULT_INTERVAL_MINUTES})",
    )
    loop_p.add_argument(
        "--json",
        action="store_true",
        dest="json_output",
        help="Output results as JSON",
    )

    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Enable debug logging",
    )

    args = parser.parse_args(argv)

    # Configure root logging: file handler ONLY (R-U5.2 / INV-9).  No
    # console/stream handler — agent traces and tool-call diagnostics
    # must not leak onto stdout/stderr.  The argparse subcommand may
    # still print its own contractual text/JSON below, but that is the
    # daemon's *result* line, not log output.
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        handlers=[],  # we attach the file handler explicitly below
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )

    from contents_hub.config import load_config

    config = load_config(args.vault)

    log_path = config.meta_path / "daemon.log"
    log_path.parent.mkdir(parents=True, exist_ok=True)
    file_handler = logging.FileHandler(log_path, encoding="utf-8")
    file_handler.setLevel(logging.DEBUG if args.verbose else logging.INFO)
    file_handler.setFormatter(
        logging.Formatter("%(asctime)s [%(levelname)s] %(name)s: %(message)s")
    )
    root_logger = logging.getLogger()
    root_logger.setLevel(logging.DEBUG if args.verbose else logging.INFO)
    root_logger.addHandler(file_handler)
    root_logger.info("daemon log file: %s", log_path)

    if args.action == "run":
        result = asyncio.run(daemon_tick(config))

        if getattr(args, "json_output", False):
            output = {
                "total": result.total,
                "new": result.new,
                "skipped": result.skipped,
                "errors": result.errors,
                "duration_seconds": round(result.duration_seconds, 2),
            }
            print(json.dumps(output, indent=2, ensure_ascii=False))
        else:
            print(
                f"Checked {result.total} subscriptions "
                f"({result.total - result.errors} ok, {result.errors} error)"
            )
            print(
                f"New items: {result.new}, "
                f"Skipped: {result.skipped}"
            )
            print(f"Duration: {result.duration_seconds:.1f}s")

            for ps in result.per_subscription:
                status = "x" if not ps.ok else "ok"
                detail = ps.error if ps.error else f"+{ps.new_items} new"
                print(f"  [{status}] {ps.url}: {detail}")

        return 0

    elif args.action == "loop":
        interval = getattr(args, "interval", DEFAULT_INTERVAL_MINUTES)

        def _print_result(result: DaemonTickResult) -> None:
            ts = datetime.now(timezone.utc).strftime("%H:%M:%S")
            print(
                f"[{ts}] {result.total} subs, "
                f"+{result.new} new, "
                f"{result.errors} errors"
            )

        asyncio.run(
            daemon_loop(
                config,
                interval_minutes=interval,
                on_complete=_print_result,
            )
        )
        return 0

    return 1


# Re-export DaemonTickResult for callers that import it from this module.
__all__ = [
    "BACKOFF_MINUTES",
    "DaemonTickResult",
    "DEFAULT_INTERVAL_MINUTES",
    "backoff_minutes",
    "classify_error",
    "daemon_loop",
    "daemon_tick",
    "main",
]


if __name__ == "__main__":
    raise SystemExit(main())
